<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3968" started-at="2018-06-25T00:03:03Z" finished-at="2018-06-25T00:03:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3968" started-at="2018-06-25T00:03:03Z" finished-at="2018-06-25T00:03:07Z">
      <class name="com.FutureItVisionFramework.searchtest.HomePageSearchTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.FutureItVisionFramework.searchtest.HomePageSearchTest@6f7fd0e6]" name="init" is-config="true" duration-ms="3781" started-at="2018-06-25T00:03:03Z" finished-at="2018-06-25T00:03:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="verifysearchButton()[pri:0, instance:com.FutureItVisionFramework.searchtest.HomePageSearchTest@6f7fd0e6]" name="verifysearchButton" duration-ms="63" started-at="2018-06-25T00:03:07Z" finished-at="2018-06-25T00:03:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.FutureItVisionFramework.searchtest.HomePageSearchTest.verifysearchButton(HomePageSearchTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifysearchButton -->
        <test-method status="PASS" signature="endSession()[pri:0, instance:com.FutureItVisionFramework.searchtest.HomePageSearchTest@6f7fd0e6]" name="endSession" is-config="true" duration-ms="108" started-at="2018-06-25T00:03:07Z" finished-at="2018-06-25T00:03:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
      </class> <!-- com.FutureItVisionFramework.searchtest.HomePageSearchTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
